
trigger:
- master

pool:
  name: default

steps: 
-  script: echo hello world

- task: Leapwork@4
  inputs:
    leapworkHostname: 'localhost'
    leapworkPort: '9001'
    leapworkAccessKey: 'qwerty'
    leapworkDoneStatusAs: 'Failed'
    leapworkReport: 'report.xml'
    leapworkSchids: '89e5ee7c-01f6-4192-8362-16ec3721821a'




